openTraining/apps/sync/urls.py
from django.conf.urls import url

from openTraining.apps.sync import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^journal/(?P<year>\d+)/(?P<month>\d+)/$', views.journal, name='activity_list'),
    url(r'^journal/$', views.journal, name='journal'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^bilan/$', views.bilan, name='bilan'),
    url(r'^bilan/(?P<year>\d+)/$', views.bilan, name='bilan'),
    url(r'^synchroniser/$', views.synchroniser, name='synchroniser'),
    url(r'^charges/$', views.charges, name='charges'),
    url(r'^charges/(?P<year>\d+)/(?P<week>\d+)/$', views.charges, name='charges'),
]

openTraining/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('openTraining.apps.sync.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

openTraining/apps/sync/models.py
import datetime

from django.db import models
from django.utils.formats import date_format, time_format
from django.utils.translation import gettext as _


class Synchronization(models.Model):
    """
    Synchronization
    """
    date = models.DateTimeField(auto_now_add=True, verbose_name="date de la synchronisation")

    def __str__(self):
        return _("{date} à {time}".format(
            date=date_format(self.date, 'l j F Y'),
            time=time_format(self.date)
        ))


class Activity(models.Model):
    """
    Activité
    """
    SWIM = 1
    RIDE = 2
    RUN = 3
    FOOTBALL = 4
    OTHER = 5
    TYPE = (
        (SWIM, "Natation"),
        (RIDE, "Vélo"),
        (RUN, "Course à pied"),
        (FOOTBALL, "Football"),
        (OTHER, "Autre")
    )

    strava_id = models.BigIntegerField(
        verbose_name="identifiant strava"
    )
    name = models.CharField(
        max_length=100,
        verbose_name="nom"
    )
    distance = models.FloatField(
        verbose_name="distance"
    )
    moving_time = models.IntegerField(
        verbose_name="durée de déplacement"
    )
    elapsed_time = models.IntegerField(
        verbose_name="durée de l'activité"
    )
    total_elevation_gain = models.FloatField(
        blank=True,
        null=True,
        verbose_name="dénivelé"
    )
    elev_high = models.FloatField(
        blank=True,
        null=True,
        verbose_name="altitude maximale"
    )
    elev_low = models.FloatField(
        blank=True,
        null=True,
        verbose_name="altitude minimale"
    )
    type = models.IntegerField(
        choices=TYPE,
        verbose_name="sport"
    )
    date = models.DateTimeField(
        verbose_name="date de l'activité"
    )
    average_speed = models.FloatField(
        verbose_name="vitesse moyenne"
    )
    max_speed = models.FloatField(
        verbose_name="vitesse maximale"
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name="description"
    )
    average_heartrate = models.IntegerField(
        verbose_name="fréquence cardiaque moyenne",
        blank=True,
        null=True
    )
    max_heartrate = models.IntegerField(
        verbose_name="fréquence cardiaque maximum",
        blank=True,
        null=True
    )

    class Meta:
        unique_together = ('strava_id',)


class Wellness(models.Model):
    """
    Forme
    """
    date = models.DateTimeField(
        verbose_name="date de l'activité"
    )
    value = models.IntegerField(
        verbose_name="Valeur"
    )

    class Meta:
        unique_together = ('date',)

openTraining/apps/sync/forms.py
# coding : utf-8
from django import forms


class WellnessForm(forms.Form):
    humeur = forms.IntegerField()
    sommeil = forms.IntegerField()
    musculaire = forms.IntegerField()
    stress = forms.IntegerField()
    fatigue = forms.IntegerField()

openTraining/apps/sync/views.py
import datetime
from collections import OrderedDict

from django.db.models import Avg, Count, Sum
from django.shortcuts import render
from django.utils.formats import date_format

from openTraining.apps.sync.forms import WellnessForm
from openTraining.apps.sync.models import Activity, Synchronization, Wellness
from openTraining.apps.sync.tasks import synchronization


def dashboard(request):
    """
    Dashboard d'accueil
    :param request:
    :return:
    """
    current_date = datetime.datetime.now()
    start = current_date - datetime.timedelta(days=current_date.weekday())
    end = start + datetime.timedelta(days=6)
    activities = Activity.objects.filter(date__date__gte=start, date__date__lte=end)

    resume = dict()
    resume['swim'] = activities.filter(type=Activity.SWIM).aggregate(
        duration=Sum('elapsed_time'),
        distance=Sum('distance')
    )
    resume['bike'] = activities.filter(type=Activity.RIDE).aggregate(
        duration=Sum('elapsed_time'),
        distance=Sum('distance')
    )
    resume['run'] = activities.filter(type=Activity.RUN).aggregate(
        duration=Sum('elapsed_time'),
        distance=Sum('distance')
    )

    last_five = Activity.objects.order_by("-date")[:5]

    wellness = Wellness.objects.filter(date=current_date.date()).first()

    if request.method == 'POST':
        wellness_form = WellnessForm(request.POST)
        if wellness_form.is_valid():
            humeur = wellness_form.cleaned_data['humeur']
            sommeil = wellness_form.cleaned_data['sommeil']
            musculaire = wellness_form.cleaned_data['musculaire']
            stress = wellness_form.cleaned_data['stress']
            fatigue = wellness_form.cleaned_data['fatigue']
            result = (humeur + sommeil + musculaire + stress + fatigue) / 5
            wellness = Wellness.objects.create(date=datetime.datetime.now().date(), value=result)
    else:
        wellness_form = WellnessForm()

    return render(
        request, 'sync/dashboard.html', {
            'activities': last_five, 'resume': resume, 'form': wellness_form, 'wellness': wellness})


def journal(request, month=None, year=None):
    """
    Liste des activités pour un mois
    :param year:
    :param month:
    :param request:
    :return:
    """
    if not month and not year:
        current_date = datetime.datetime.now()
        month = current_date.month
        year = current_date.year
    else:
        current_date = datetime.datetime(int(year), int(month), 1)

    activities = Activity.objects.all().filter(date__month=month, date__year=year).order_by('-date')
    summary = activities.aggregate(count=Count('id'), duration=Sum('elapsed_time'), distance=Sum('distance'))

    return render(
        request, 'sync/journal.html', {
            'activities': activities, 'current_date': current_date, 'summary': summary})


def synchroniser(request):
    """
    Synchronisation des activités
    :param request:
    :return:
    """
    data = {}
    sync = request.GET.get('sync', False)
    data['sync'] = sync
    if not sync:
        last_synchronisation = Synchronization.objects.last()
        data['last'] = last_synchronisation
    else:
        created = synchronization()
        data['created'] = created
    return render(request, 'sync/synchroniser.html', data)


def bilan(request, year=None):
    """
    Bilan mois par mois sur une année
    :param request:
    :param year:
    :return:
    """
    data = {}
    resume = {}
    resume_run = OrderedDict()
    resume_ride = OrderedDict()
    resume_swim = OrderedDict()
    resume_football = OrderedDict()
    resume_other = OrderedDict()

    if not year:
        current_date = datetime.datetime.now()
        year = current_date.year
    else:
        current_date = datetime.datetime(int(year), 1, 1)
    data['current_date'] = current_date

    year_activities = Activity.objects.filter(date__year=year)

    total = {}
    for sport in dict(Activity.TYPE).keys():
        total[sport] = year_activities.filter(type=sport).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            speed=Avg('average_speed'))

    for month in range(1, 13):
        current_month = datetime.datetime(int(year), month, 1)
        month_activities = year_activities.filter(date__month=current_month.month)

        resume_swim[date_format(current_month, 'F')] = month_activities.filter(type=Activity.SWIM).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            speed=Avg('average_speed'))
        resume_ride[date_format(current_month, 'F')] = month_activities.filter(type=Activity.RIDE).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            speed=Avg('average_speed'))
        resume_run[date_format(current_month, 'F')] = month_activities.filter(type=Activity.RUN).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            speed=Avg('average_speed'))
        resume_football[date_format(current_month, 'F')] = month_activities.filter(type=Activity.FOOTBALL).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            speed=Avg('average_speed'))
        resume_other[date_format(current_month, 'F')] = month_activities.filter(type=Activity.OTHER).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            speed=Avg('average_speed'))

    resume['swim'] = resume_swim
    resume['ride'] = resume_ride
    resume['run'] = resume_run
    resume['foot'] = resume_football
    resume['other'] = resume_other
    data['resume'] = resume
    data['total'] = total

    return render(request, 'sync/bilan.html', data)


def charges(request, year=None, week=None):
    """
    Charges hebdomadaires
    :param request:
    :param year:
    :param week:
    :return:
    """
    def firstdayinweek(y, w):
        ret = datetime.datetime.strptime('{year}-{week}-1'.format(year=y, week=w), '%Y-%W-%w')
        if datetime.date(int(y), 1, 4).isoweekday() > 4:
            ret -= datetime.timedelta(days=7)
        return ret
    if not year:
        current_date = datetime.datetime.now()
        start = current_date - datetime.timedelta(days=current_date.weekday())
    else:
        start = firstdayinweek(year, week)
    end = start + datetime.timedelta(days=6)

    activities = Activity.objects.filter(date__date__gte=start, date__date__lte=end)

    resume = dict()
    resume['swim'] = activities.filter(type=Activity.SWIM).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            heart=Avg('average_heartrate'),
            speed=Avg('average_speed'))
    resume['ride'] = activities.filter(type=Activity.RIDE).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            heart=Avg('average_heartrate'),
            speed=Avg('average_speed'))
    resume['run'] = activities.filter(type=Activity.RUN).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            heart=Avg('average_heartrate'),
            speed=Avg('average_speed'))
    resume['football'] = activities.filter(type=Activity.FOOTBALL).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            heart=Avg('average_heartrate'))
    resume['other'] = activities.filter(type=Activity.OTHER).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            heart=Avg('average_heartrate'),
            speed=Avg('average_speed'))
    current_week = activities.aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            heart=Avg('average_heartrate'),
            speed=Avg('average_speed'))
    resume['summary'] = current_week

    start_last_week = start - datetime.timedelta(weeks=1)
    end_last_week = start_last_week + datetime.timedelta(days=6)
    last_week = Activity.objects.filter(date__date__gte=start_last_week, date__date__lte=end_last_week).aggregate(
            count=Count('id'),
            duration=Sum('elapsed_time'),
            distance=Sum('distance'),
            heart=Avg('average_heartrate'),
            speed=Avg('average_speed'))

    data = dict()
    data['pourcent'] = round(
        ((current_week.get('duration', 0) or 0) - last_week.get('duration', 0)) / last_week.get('duration', 0) * 100)\
        if last_week.get('duration', None) else None
    data['duration'] = (current_week.get('duration', 0) or 0) - (last_week.get('duration', 0) or 0)
    data['distance'] = (current_week.get('distance', 0) or 0) - (last_week.get('distance', 0) or 0)

    data = {'start': start, 'end': end, 'resume': resume, 'charges': data}

    return render(request, 'sync/charges.html', data)

openTraining/apps/sync/templates/sync/activity_list2.html
{% extends 'sync/base.html' %}
{% load sync_extras %}
{% block content %}

    <div class="row">
        <div class="col-md-2">
            <a class="btn btn-primary" href="/activities/{{ current_date | previous_month | date:'Y/m/' }}" tabindex="-1">&laquo;</a>
        </div>
        <div class="col-md-8 text-center">
            <h4>{{ current_date | date:"F Y" | capfirst }}</h4>
        </div>
        <div class="col-md-2 text-right">
            <a class="btn btn-primary" href="/activities/{{ current_date | next_month | date:'Y/m/' }}">&raquo;</a>
        </div>
    </div>

    <div class="opentraining-block">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="text-center">Date</th>
                    <th class="text-center">Sport</th>
                    <th class="text-center">Titre</th>
                    <th class="text-center">Durée</th>
                    <th class="text-center">Fréquence cardiaque</th>
                    <th class="text-center">Distance</th>
                    <th class="text-center">Allure/Vitesse</th>
                </tr>
            </thead>
            <tbody>
            {% for activity in activities %}
                <tr>
                    <th scope="row" class="text-center">{{ activity.date | date:"d/m/Y" }}</th>
                    <td class="text-center">{{ activity.get_type_display }}</td>
                    <td class="text-center">{{ activity.name }}</td>
                    <td class="text-center">{{ activity.elapsed_time | duration }}</td>
                    <td class="text-center">{{ activity.average_heartrate | default:'-' }}</td>
                    <td class="text-center">{{ activity.distance | distance_to_km }}</td>
                    <td class="text-center">
                        {% if activity.type == 3 %}
                            {{ activity.average_speed | speed_to_minkm | default:'-' }}
                        {% elif activity.type == 1 %}
                            {{ activity.average_speed | speed_to_minnat | default:'-' }}
                        {% else %}
                            {{ activity.average_speed | speed_to_kmh | default:'-' }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
                <tr class="table-active">
                    <td class="text-center"><strong>Total</strong></td>
                    <td colspan="2" class="text-center"><strong>{{ summary.count }} activités</strong></td>
                    <td class="text-center"><strong>{{ summary.duration | duration }}</strong></td>
                    <td></td>
                    <td class="text-center"><strong>{{ summary.distance | distance_to_km }}</strong></td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>
{% endblock %}

openTraining/apps/sync/templates/sync/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>openTraining</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/opentraining.css' %}">
    <link rel="stylesheet" href="{% static 'css/circle.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">OpenTraining</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Dashboard <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/journal/">Journal</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/bilan/">Bilan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/charges/">Charges</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/synchroniser/">Synchroniser</a>
            </li>
        </ul>
      </div>
    </nav>
    <div class="mx-5 opentraining-content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

openTraining/apps/sync/templates/sync/dashboard.html
{% extends 'sync/base.html' %}
{% load sync_extras %}
{% load static %}
{% block content %}

    <div class="row">

        <!--#region Forme du jour -->
        <div class="col-6">
            <div class="opentraining-panel mt-4 shadow">
                {% if wellness %}
                    <h1>Forme du jour</h1>
                    <div class="mt-4">
                        <div class="row justify-content-md-center">
                            <div class="col-4 col-auto">
                            <div class="c100 p{{ wellness.value }}">
                                <span>{{ wellness.value | floatformat:'0' }}%</span>
                                <div class="slice">
                                    <div class="bar"></div>
                                    <div class="fill"></div>
                                </div>
                            </div>
                                </div>
                        </div>
                    </div>
                {% else %}
                    <form action="/dashboard/" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <h1 class="col-6">Forme du jour</h1>
                            <div class="col-6 text-right">
                                <button type="submit" class="btn btn-primary">Enregistrer</button>
                            </div>
                        </div>
                        <div class="mt-4">
                            <div class="form-group row">
                                <label for="id_humeur" class="col-3 col-form-label opentraining-panel-font">Humeur</label>
                                <div class="col-9">
                                    <input type="range" name="humeur" required id="id_humeur" min="0" max="100" step="10"/>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_sommeil" class="col-3 col-form-label opentraining-panel-font">Sommeil</label>
                                <div class="col-9">
                                    <input type="range" name="sommeil" required id="id_sommeil" min="0" max="100" step="10"/>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_musculaire" class="col-3 col-form-label opentraining-panel-font">Musculaires</label>
                                <div class="col-9">
                                    <input type="range" name="musculaire" required id="id_musculaire" min="0" max="100" step="10"/>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_stress" class="col-3 col-form-label opentraining-panel-font">Stress</label>
                                <div class="col-9">
                                    <input type="range" name="stress" required id="id_stress" min="0" max="100" step="10"/>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_fatigue" class="col-3 col-form-label opentraining-panel-font">Fatigue</label>
                                <div class="col-9">
                                    <input type="range" name="fatigue" required id="id_fatigue" min="0" max="100" step="10"/>
                                </div>
                            </div>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
        <!--#endregion -->

        <!--#region Dernière activités -->
        <div class="col-6">
            <div class="opentraining-panel mt-4 shadow">
                <h1>Dernière(s) activité(s)</h1>
                <div class="content mt-4">
                    {% for activity in activities %}
                        <div class="row pb-3">
                            <div class="ml-3">
                                {% if activity.type == 1 %}
                                    <img src="{% static 'img/swimming.png' %}" class="opentraining-image" alt="Natation" title="Natation"/>
                                {% elif activity.type == 2 %}
                                    <img src="{% static 'img/cycling.png' %}" class="opentraining-image" alt="Vélo" title="Vélo"/>
                                {% elif activity.type == 3 %}
                                    <img src="{% static 'img/running.png' %}" class="opentraining-image" alt="Course à pied" title="Course à pied"/>
                                {% else %}
                                    <img src="{% static 'img/autres.png' %}" class="opentraining-image" alt="Autres" title="Autres"/>
                                {% endif %}
                            </div>
                            <div class="col-9 ml-2">
                                <div class="opentraining-panel-font">{{ activity.name }} - {{ activity.elapsed_time | seconds_to_minutes }} min</div>
                                <div class="opentraining-panel-foot">{{ activity.date | date:"d/m/Y H:i"}}</div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!--#endregion -->
    </div>
    <!--#region Récapitulatif hebdo-->
    <div class="row mt-3">
        <div class="col-12">
            <div class="opentraining-panel mt-4 shadow">
                <h1>Récapitulatif hebdomadaire</h1>
                <div class="row mt-4">
                    <div class="col-4">
                        <div class="row">
                            <div class="ml-3">
                                <img src="{% static 'img/swimming.png' %}" class="opentraining-image" alt="Natation" title="Natation"/>
                            </div>

                            <div class="col-9">
                                <div class="row mb-1">
                                    <div class="col opentraining-recap-distance">{{ resume.swim.duration | duration }}</div>
                                    <div class="col justify-content-between text-right">{{ resume.swim.distance | swim_arround | floatformat:"0" }} m</div>
                                </div>
                                <div class="progress" style="height: 0.5em">
                                  <div class="progress-bar bg-info" role="progressbar" style="width: {% if resume.swim.duration %}100%{% else %}0{% endif %}" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row">
                            <div class="ml-3">
                                <img src="{% static 'img/cycling.png' %}" class="opentraining-image" alt="Vélo" title="Vélo"/>
                            </div>

                            <div class="col-9">
                                <div class="row mb-1">
                                    <div class="col opentraining-recap-distance">{{ resume.bike.duration | duration }}</div>
                                    <div class="col justify-content-between text-right">{{ resume.bike.distance | distance_to_km | floatformat:"1" }} km</div>
                                </div>
                                <div class="progress" style="height: 0.5em">
                                  <div class="progress-bar bg-info" role="progressbar" style="width: {%  if resume.bike.duration %}100%{% else %}0{% endif %}" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row">
                            <div class="ml-3">
                                <img src="{% static 'img/running.png' %}" class="opentraining-image" alt="Course à pied" title="Course à pied"/>
                            </div>

                            <div class="col-9">
                                <div class="row mb-1">
                                    <div class="col opentraining-recap-distance">{{ resume.run.duration | duration  }}</div>
                                    <div class="col justify-content-between text-right">{{ resume.run.distance | distance_to_km | floatformat:"1" }} km</div>
                                </div>
                                <div class="progress" style="height: 0.5em">
                                  <div class="progress-bar bg-info" role="progressbar" style="width: {%  if resume.run.duration %}100%{% else %}0{% endif %}" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--#endregion -->
{% endblock %}

openTraining/apps/sync/templates/sync/journal.html
{% extends 'sync/base.html' %}
{% load sync_extras %}
{% block content %}

    <div class="row">
        <div class="col-md-2">
            <a class="btn btn-primary" href="/journal/{{ current_date | previous_month | date:'Y/m/' }}" tabindex="-1">&laquo;</a>
        </div>
        <div class="col-md-8 text-center">
            <h4>{{ current_date | date:"F Y" | capfirst }}</h4>
        </div>
        <div class="col-md-2 text-right">
            <a class="btn btn-primary" href="/journal/{{ current_date | next_month | date:'Y/m/' }}">&raquo;</a>
        </div>
    </div>

    <div class="opentraining-block">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="text-center">Date</th>
                    <th class="text-center">Sport</th>
                    <th class="text-center">Titre</th>
                    <th class="text-center">Durée</th>
                    <th class="text-center">Fréquence cardiaque</th>
                    <th class="text-center">Distance</th>
                    <th class="text-center">Allure/Vitesse</th>
                </tr>
            </thead>
            <tbody>
            {% for activity in activities %}
                <tr>
                    <th scope="row" class="text-center">{{ activity.date | date:"d/m/Y" }}</th>
                    <td class="text-center">{{ activity.get_type_display }}</td>
                    <td class="text-center">{{ activity.name }}</td>
                    <td class="text-center">{{ activity.elapsed_time | duration }}</td>
                    <td class="text-center">{{ activity.average_heartrate | default:'-' }}</td>
                    <td class="text-center">{{ activity.distance | distance_to_km }}</td>
                    <td class="text-center">
                        {% if activity.type == 3 %}
                            {{ activity.average_speed | speed_to_minkm | default:'-' }}
                        {% elif activity.type == 1 %}
                            {{ activity.average_speed | speed_to_minnat | default:'-' }}
                        {% else %}
                            {{ activity.average_speed | speed_to_kmh | default:'-' }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
                <tr class="table-active">
                    <td class="text-center"><strong>Total</strong></td>
                    <td colspan="2" class="text-center"><strong>{{ summary.count }} activités</strong></td>
                    <td class="text-center"><strong>{{ summary.duration | duration }}</strong></td>
                    <td></td>
                    <td class="text-center"><strong>{{ summary.distance | distance_to_km }}</strong></td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>
{% endblock %}

openTraining/apps/sync/templates/sync/synchroniser.html
{% extends 'sync/base.html' %}

{% block content %}
    <div class="opentraining-block text-center">
        {% if not sync %}
            <h3>Synchroniser les activités récentes</h3>
            <a href="/synchroniser/?sync=True" class="btn btn-primary">Démarrer</a>
            <p class="text-muted"><small>Dernière synchronisation : {{ last | default:'aucune'}}</small></p>
        {% else %}
            <h3>Synchronisation terminée</h3>
            <a href="/" class="btn btn-primary">Retour</a>
        {% endif %}
    </div>
{% endblock %}